name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  hello_world_job: 
    runs-on: ubuntu-latest 
    name: A job to say hello 
    steps: 
    - name: Hello world action step 
      id: hello 
      uses: unaihuete-org/hello-world-action@v1 
      with: 
        who-to-greet: 'your-name' 
    - name: Get the output time 
      run: echo "The time was ${{ steps.hello.outputs.time }}" 
